@baseUrl = http://127.0.0.1:5000

###

POST {{baseUrl}}/categorias
Content-Type: application/json

{
    "nome": "Programação"
}

###

POST {{baseUrl}}/categorias
Content-Type: application/json

{
    "nome": "Tio do Pavê"
}

###

GET {{baseUrl}}/categorias/1

###

GET {{baseUrl}}/categorias

###

PUT {{baseUrl}}/categorias/2
Content-Type: application/json

{
    "nome": "Piadas de Tiozinho"
}

###

POST {{baseUrl}}/piadas
Content-Type: application/json

{
    "pergunta": "Por que o computador foi ao médico?",
    "resposta": "Porque ele estava com um vírus!",
    "categoria_id": 1
}

###

POST {{baseUrl}}/piadas
Content-Type: application/json

{
    "pergunta": "Qual é a ferramenta favorita dos desenvolvedores?",
    "resposta": "O garfo, porque tem muitos forks!",
    "categoria_id": 1
}

###

POST {{baseUrl}}/piadas
Content-Type: application/json

{
    "pergunta": "É pavê ou pra comer?",
    "resposta": "É pra comer!",
    "categoria_id": 2
}

###

GET {{baseUrl}}/piadas

###

GET {{baseUrl}}/piadas/1

###

PUT {{baseUrl}}/piadas/1
Content-Type: application/json

{
    "pergunta": "Por que o computador foi ao hospital?",
    "resposta": "Porque estava com vírus!",
    "categoria_id": 1
}

###

GET {{baseUrl}}/piadas/detalhes

###

GET {{baseUrl}}/categorias/1/piadas

###

GET {{baseUrl}}/piadas/busca?q=computador

###

DELETE {{baseUrl}}/piadas/2

###

DELETE {{baseUrl}}/categorias/1
